### ISSUE TITLE
[JOSS] Broken link for "Code of conduct" in the "CONTRIBUTING.MD" page

### ISSUE THREAD

**Issue by mathieuboudreau** [ritagnunes/PulseqDiffusion#2]
The link to the code of conduct in the "Contributing" page points to: https://github.com/ritagnunes/PulseqDiffusion/blob/master/code_of_conduct

which does not exist. Instead, it should point to: https://github.com/ritagnunes/PulseqDiffusion/blob/master/CODE_OF_CONDUCT.md

**Comment by sravan953** [comment]
@mathieuboudreau could you please let us know if this issue can be closed?

**Comment by mathieuboudreau** [comment]
The link is functional now, thanks!
