### ISSUE TITLE
[JOSS] suggested fix to function name/terminology

### ISSUE THREAD

**Issue by grlee77** [ritagnunes/PulseqDiffusion#7]
**Describe the bug**
The `LongSS_Signal` function claims to be calculating the steady-state **longitudinal** signal, but is actual calculating the **transverse** signal. The name of the function & documentation should be updated to reflect that.

Specifically, in the following line
https://github.com/ritagnunes/PulseqDiffusion/blob/4ca565201a5334c8f6954575c1f7302198bc2bbb/PulseqDiffusion/SNR_CNR_Study/LongSS_Signal.m#L14
The steady-state longitudinal signal is the `(1-exp(-TRep/T1))./(1-(exp(-TRep/T1)).*cosd(FlipAngle))` term, while the sine and T2 decay terms out front relate this to the observed MRI signal in the transverse plane.

**To Reproduce**
N/A

**Expected behavior**
update the function documentation and name

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by ZemaTimoteo** [comment]
We thank the reviewer for this comment. We have update the function documentations and names. The functions, in the folder _PulseqDiffusion/PulseqDiffusion/SNR_CNR_Study/_ : **TransvSS_Signal.m** ; **TransvSS_SignalTest.m**  and  **SNR_CNR_Study_Simulation.m** were updated. Also, the file **TransvSS_Signal_TestResults.mat**, in the folder _PulseqDiffusion/PulseqDiffusion/SNR_CNR_Study/Example_Data/_,  was renamed.
